const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const dayNumber=Math.floor(Date.now()/86400000), saved=JSON.parse(localStorage.getItem("gwg_stats")||"{}");
const state={game:"crossword",difficulty:"easy",seconds:0,puzzle:dayNumber%100,moves:0,pairs:0,pairGoal:8,firstCard:null,lock:false,crossWords:[],wordTargets:[],hints:0,hintsUsed:0,bonusHints:0,adTimer:null,stats:{completed:saved.completed||0,best:saved.best||0,totalScore:saved.totalScore||0,streak:saved.streak||0,lastDay:saved.lastDay||0}};
const adConfig=window.GOLDEN_AD_CONFIG||{}, AD_PAGE_URL=adConfig.adPageUrl||"https://example.com/", SPONSOR_URL=adConfig.sponsorWebsiteUrl||AD_PAGE_URL, AD_DURATION=Math.max(5,Number(adConfig.durationSeconds)||30), AD_CTA_AFTER=Math.max(0,Number(adConfig.ctaAppearsAfterSeconds)||10);
const toast=msg=>{const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)};
const openModal=id=>$(id).classList.add("open"), closeModals=()=>$$(".modal-backdrop").forEach(m=>m.classList.remove("open"));
function enterFullScreen(){const el=document.documentElement;if(!document.fullscreenElement&&el.requestFullscreen)el.requestFullscreen().catch(()=>toast("Your browser did not allow full screen."))}
function seeded(seed){return()=>{seed=Math.imul(seed^seed>>>15,1|seed);seed^=seed+Math.imul(seed^seed>>>7,61|seed);return((seed^seed>>>14)>>>0)/4294967296}}
const shuffle=(a,r=Math.random)=>a.map(v=>[r(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]), levelCount={easy:5,medium:7,hard:9};
const wordBanks={
easy:[["APPLE","A crisp fruit"],["TRAIN","Railway traveler"],["HOUSE","A place to live"],["WATER","Drink from a glass"],["MUSIC","Pleasant sound"],["BEACH","Sandy shore"],["CHAIR","A seat"],["SMILE","Happy expression"],["CLOCK","It tells time"],["RIVER","Flowing water"],["BREAD","Bakery staple"],["LIGHT","Opposite of dark"],["GARDEN","Place for flowers"],["FAMILY","Parents and children"],["ROAD","Route for cars"]],
medium:[["LIBERTY","Freedom"],["JOURNEY","A long trip"],["HARVEST","Gathering crops"],["THEATER","Place for a stage show"],["MOUNTAIN","Very high land"],["HISTORY","Study of the past"],["BASEBALL","American pastime"],["BALLOON","Inflated party decoration"],["COUNTRY","A nation"],["AIRPORT","Place to catch a flight"],["MORNING","Start of the day"],["LIBRARY","Home of many books"],["PICNIC","Outdoor meal"],["HIGHWAY","Major road"],["WEATHER","Outdoor conditions"]],
hard:[["BLUEPRINT","Detailed building plan"],["DISCOVERY","Finding something new"],["LANDSCAPE","Visible features of land"],["KNOWLEDGE","Facts and understanding"],["CELEBRATE","Mark a happy occasion"],["ADVENTURE","An exciting experience"],["COMMUNITY","People living together"],["TRADITION","Custom passed through generations"],["WILDERNESS","Uncultivated natural region"],["PRESIDENT","Head of the US executive branch"],["TELESCOPE","Instrument for distant objects"],["MASTERPIECE","Outstanding creative work"],["NAVIGATION","Finding a route"],["MEMORABLE","Worth remembering"],["GENERATION","People born in a similar period"]]};
function placeCrossword(entries){const size=15,board=Array.from({length:size},()=>Array(size).fill("")),placed=[],first=entries[0],sx=Math.floor((size-first[0].length)/2),sy=7;first[0].split("").forEach((c,i)=>board[sy][sx+i]=c);placed.push({word:first[0],clue:first[1],x:sx,y:sy,dir:"across"});
for(const [word,clue] of entries.slice(1)){let done=false;for(let pi=0;pi<placed.length&&!done;pi++){const p=placed[pi];for(let a=0;a<word.length&&!done;a++)for(let b=0;b<p.word.length&&!done;b++)if(word[a]===p.word[b]){const dir=p.dir==="across"?"down":"across",x=p.x+(p.dir==="across"?b:0)-(dir==="across"?a:0),y=p.y+(p.dir==="down"?b:0)-(dir==="down"?a:0);if(x<0||y<0||(dir==="across"&&x+word.length>size)||(dir==="down"&&y+word.length>size))continue;let ok=true;for(let k=0;k<word.length;k++){const xx=x+(dir==="across"?k:0),yy=y+(dir==="down"?k:0),v=board[yy][xx];if(v&&v!==word[k])ok=false}if(ok){word.split("").forEach((c,k)=>board[y+(dir==="down"?k:0)][x+(dir==="across"?k:0)]=c);placed.push({word,clue,x,y,dir});done=true}}}}return{board,placed}}
function makeCrossword(){const r=seeded(state.puzzle*97+dayNumber+({easy:1,medium:2,hard:3}[state.difficulty])*1009),selected=shuffle(wordBanks[state.difficulty],r).slice(0,levelCount[state.difficulty]),built=placeCrossword(selected),board=built.board,placed=built.placed;state.crossWords=placed;const used=[];board.forEach((row,y)=>row.forEach((v,x)=>{if(v)used.push([x,y])}));const minX=Math.min(...used.map(v=>v[0])),maxX=Math.max(...used.map(v=>v[0])),minY=Math.min(...used.map(v=>v[1])),maxY=Math.max(...used.map(v=>v[1])),nums=new Map();placed.forEach((p,i)=>nums.set(p.x+","+p.y,i+1));const g=$("#crossGrid");g.innerHTML="";g.style.gridTemplateColumns="repeat("+(maxX-minX+1)+",1fr)";
for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const v=board[y][x],c=document.createElement("div");c.className=v?"cell":"cell block";c.dataset.xy=x+","+y;if(v){if(nums.has(c.dataset.xy))c.innerHTML="<span class='num'>"+nums.get(c.dataset.xy)+"</span>";const input=document.createElement("input");input.maxLength=1;input.dataset.answer=v;input.setAttribute("aria-label","Crossword square");input.oninput=()=>{input.value=input.value.replace(/[^a-z]/i,"").toUpperCase();markCrossWords()};c.appendChild(input)}g.appendChild(c)}
const fill=(id,dir)=>{$(id).innerHTML=placed.map((p,i)=>p.dir===dir?"<button class='clue'><b>"+(i+1)+".</b>"+p.clue+"</button>":"").join("")};fill("#acrossClues","across");fill("#downClues","down")}
function markCrossWords(){let solved=0;state.crossWords.forEach(p=>{let ok=true;for(let k=0;k<p.word.length;k++){const key=(p.x+(p.dir==="across"?k:0))+","+(p.y+(p.dir==="down"?k:0)),inp=$(".cell[data-xy='"+key+"'] input");if(!inp||inp.value!==p.word[k])ok=false}if(ok){solved++;for(let k=0;k<p.word.length;k++){const key=(p.x+(p.dir==="across"?k:0))+","+(p.y+(p.dir==="down"?k:0)),cell=$(".cell[data-xy='"+key+"']");if(cell)cell.classList.add("correct")}}});if(solved===state.crossWords.length&&solved)completeGame()}
const themes=[["American Road Trip",["HIGHWAY","MOTEL","TEXAS","BEACH","CANYON","TRAVEL","ROUTE","MAP"]],["At the Garden",["FLOWER","ROSE","SOIL","SEED","WATER","GREEN","BLOOM","SUN"]],["Classic Movies",["SCREEN","ACTOR","SCENE","TICKET","DRAMA","COMEDY","FILM","STAR"]],["Sunday Kitchen",["COFFEE","BREAD","PLATE","SPOON","APPLE","DINNER","RECIPE","OVEN"]],["Great Outdoors",["TRAIL","RIVER","CABIN","EAGLE","FOREST","LAKE","CAMP","HIKING"]]];
function makeWords(){const r=seeded(state.puzzle*181+dayNumber),themeData=themes[state.puzzle%themes.length],theme=themeData[0],bank=themeData[1],count=levelCount[state.difficulty];state.wordTargets=shuffle(bank,r).slice(0,Math.min(count,bank.length));$("#wordsearch .game-meta").innerHTML="<span>Find: <b>"+state.wordTargets.length+" words</b></span><span>Theme: <b>"+theme+"</b></span>";const size=10,rows=Array.from({length:size},()=>Array.from({length:size},()=>String.fromCharCode(65+Math.floor(r()*26)))),positions={};state.wordTargets.forEach((w,i)=>{const row=(i*2+Math.floor(r()*2))%size,start=Math.floor(r()*(size-w.length+1));positions[w]=[];w.split("").forEach((c,j)=>{rows[row][start+j]=c;positions[w].push(row*size+start+j)})});state.wordPositions=positions;const g=$("#wordGrid");g.innerHTML="";rows.flat().forEach((l,i)=>{const b=document.createElement("button");b.className="letter";b.textContent=l;b.dataset.index=i;b.onclick=()=>{b.classList.toggle("marked");checkFoundWords()};g.appendChild(b)});$("#wordBank").innerHTML=state.wordTargets.map(w=>"<span class='word-chip' data-word='"+w+"'>"+w+"</span>").join("")}
function checkFoundWords(){let found=0;state.wordTargets.forEach(w=>{const ok=state.wordPositions[w].every(i=>$$(".letter")[i].classList.contains("marked"));$("[data-word='"+w+"']").classList.toggle("found",ok);if(ok)found++});if(found===state.wordTargets.length)completeGame()}
function makeSudoku(){const base="123456789456789123789123456234567891567891234891234567345678912678912345912345678",shift=(state.puzzle+({easy:1,medium:3,hard:5}[state.difficulty]))%9;state.sudokuSolution=[...base].map(n=>((+n+shift-1)%9)+1).join("");const removals={easy:36,medium:48,hard:56}[state.difficulty],r=seeded(state.puzzle*313+dayNumber),holes=new Set(shuffle([...Array(81).keys()],r).slice(0,removals)),g=$("#sudokuGrid");g.innerHTML="";[...state.sudokuSolution].forEach((v,i)=>{const input=document.createElement("input");input.className="sudoku-cell"+(!holes.has(i)?" given":"");input.value=holes.has(i)?"":v;input.maxLength=1;input.inputMode="numeric";input.readOnly=!holes.has(i);input.dataset.answer=v;input.oninput=()=>{input.value=input.value.replace(/[^1-9]/g,"");$("#remaining").textContent=$$(".sudoku-cell").filter(x=>!x.value).length;if($$(".sudoku-cell").every(x=>x.value===x.dataset.answer))completeGame()};g.appendChild(input)});$("#remaining").textContent=removals}
const symbols=["♣","★","♪","☀","◆","♥","⚓","☕","♠","●"];
function makeMemory(){state.moves=0;state.pairs=0;state.firstCard=null;state.pairGoal={easy:6,medium:8,hard:10}[state.difficulty];$("#moves").textContent="0";$("#pairs").textContent="0 / "+state.pairGoal;const r=seeded(state.puzzle*421+dayNumber),deck=shuffle([...symbols.slice(0,state.pairGoal),...symbols.slice(0,state.pairGoal)],r),g=$("#memoryGrid");g.style.gridTemplateColumns="repeat("+(state.pairGoal===10?5:4)+",1fr)";g.innerHTML="";deck.forEach(v=>{const b=document.createElement("button");b.className="memory-card";b.dataset.symbol=v;b.textContent="?";b.onclick=()=>flipCard(b);g.appendChild(b)})}
function flipCard(b){if(state.lock||b.classList.contains("matched")||b===state.firstCard)return;b.textContent=b.dataset.symbol;b.classList.add("revealed");if(!state.firstCard){state.firstCard=b;return}state.moves++;$("#moves").textContent=state.moves;if(state.firstCard.dataset.symbol===b.dataset.symbol){b.classList.add("matched");state.firstCard.classList.add("matched");state.firstCard=null;state.pairs++;$("#pairs").textContent=state.pairs+" / "+state.pairGoal;if(state.pairs===state.pairGoal)completeGame()}else{state.lock=true;const a=state.firstCard;setTimeout(()=>{a.textContent=b.textContent="?";a.classList.remove("revealed");b.classList.remove("revealed");state.firstCard=null;state.lock=false},650)}}
const meta={crossword:["Daily Puzzle #","Crossword","Fill the crossing words using the Across and Down clues."],wordsearch:["Daily Puzzle #","Word Search","Tap every letter in each hidden word."],sudoku:["Daily Puzzle #","Sudoku","Fill every row, column, and box with the numbers 1 through 9."],memory:["Brain Boost #","Memory Match","Turn over two cards at a time and find every matching pair."]};
function resetTimer(){state.seconds=0;state.hintsUsed=0;state.bonusHints=0;updateHintButton()} function buildCurrent(){resetTimer();if(state.game==="crossword")makeCrossword();if(state.game==="wordsearch")makeWords();if(state.game==="sudoku")makeSudoku();if(state.game==="memory")makeMemory();$("#eyebrow").textContent=meta[state.game][0]+(state.puzzle+1)+" · refreshes daily"}
function switchGame(game){state.game=game;$$(".navbtn[data-game]").forEach(b=>b.classList.toggle("active",b.dataset.game===game));$$(".game-view").forEach(v=>v.classList.toggle("active",v.id===game));$("#gameTitle").textContent=meta[game][1];$("#gameSub").textContent=meta[game][2];$("#sidebar").classList.remove("open");buildCurrent()}
function checkAnswers(){let right=0,total=0;if(state.game==="crossword"){$$("#crossGrid input").forEach(i=>{total++;const c=i.parentElement;c.classList.remove("correct","wrong");if(i.value===i.dataset.answer){right++;c.classList.add("correct")}else if(i.value)c.classList.add("wrong")})}else if(state.game==="sudoku"){$$(".sudoku-cell").forEach(i=>{if(!i.readOnly){total++;i.style.background=i.value===i.dataset.answer?"#d8f2e3":i.value?"#ffd9d6":"white";if(i.value===i.dataset.answer)right++}})}else return toast("Words and pairs are checked automatically.");toast(right+" of "+total+" entries are correct.")}
function updateHintButton(){const free=Math.max(0,2-state.hintsUsed);$("#hintBtn").textContent=free?"Hint ("+free+" free)":state.bonusHints?"Use earned hint":"Watch ad for hint"}
function performHint(){state.hints++;if(state.game==="crossword"){const x=$$("#crossGrid input").find(i=>!i.value);if(x){x.value=x.dataset.answer;x.style.color="#e96f2d";markCrossWords()}}else if(state.game==="sudoku"){const x=$$(".sudoku-cell").find(i=>!i.value);if(x){x.value=x.dataset.answer;x.style.color="#e96f2d"}}else if(state.game==="wordsearch")toast("Look from left to right across each row.");else toast("Try remembering the position, not just the symbol.")}
function hint(){if(state.hintsUsed<2){state.hintsUsed++;performHint();updateHintButton();return}if(state.bonusHints>0){state.bonusHints--;performHint();updateHintButton();return}startRewardAd(true)}
function winningSound(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.setValueAtTime(523,a.currentTime);o.frequency.setValueAtTime(659,a.currentTime+.12);o.frequency.setValueAtTime(784,a.currentTime+.24);g.gain.setValueAtTime(.08,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.55);o.start();o.stop(a.currentTime+.56)}catch(e){}}
const formatTime=s=>String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0");
function completeGame(){if($("#winModal").classList.contains("open"))return;const mult={easy:1,medium:1.4,hard:1.8}[state.difficulty],score=Math.max(100,Math.round((1400-state.seconds*3-state.hints*75)*mult));state.stats.completed++;state.stats.totalScore+=score;state.stats.best=Math.max(state.stats.best,score);if(state.stats.lastDay===dayNumber-1)state.stats.streak++;else if(state.stats.lastDay!==dayNumber)state.stats.streak=1;state.stats.lastDay=dayNumber;localStorage.setItem("gwg_stats",JSON.stringify(state.stats));$("#winScore").textContent=score.toLocaleString()+" points";$("#winMessage").textContent="Completed in "+formatTime(state.seconds)+" on "+state.difficulty+" difficulty.";$("#winModal").classList.add("open");$("#confetti").classList.add("show");winningSound();setTimeout(()=>$("#confetti").classList.remove("show"),2500);renderStats()}
function showInfo(title,html){$("#infoTitle").textContent=title;$("#infoBody").innerHTML=html;openModal("#infoModal")}
function renderStats(){const names=["MapleSue","RoadTripRay","BlueJay55","GardenGal","JazzFan","TexasTom","CarolP","PuzzlePat","SunnySam","OhioRose","LakeLou","BostonBill","NanaJo","CoachKen","DaisyM","SilverFox","JuneB","MaineMike","HappyHal","WordWiz"];$("#rankings").innerHTML=names.slice(0,5).map((n,i)=>"<div class='rank-row'><b>"+(i+1)+"</b><span class='avatar'>"+n[0]+"</span><span>"+n+"</span><span class='score'>"+(1620-i*47).toLocaleString()+"</span></div>").join("");$(".streak strong").textContent=state.stats.streak+"-day streak"}
function startRewardAd(rewardHint=false){if(state.adTimer)clearInterval(state.adTimer);let n=AD_DURATION;enterFullScreen();$("#adFrame").src=AD_PAGE_URL;$("#adCount").textContent=n;$("#adStatus").textContent=rewardHint?"Watch completely to earn a hint":"Sponsored game preview";$("#adCta").classList.remove("show");openModal("#rewardAd");state.adTimer=setInterval(()=>{n--;$("#adCount").textContent=n;if(AD_DURATION-n>=AD_CTA_AFTER)$("#adCta").classList.add("show");if(n<=0){clearInterval(state.adTimer);state.adTimer=null;$("#adFrame").src="about:blank";$("#rewardAd").classList.remove("open");if(rewardHint){state.bonusHints++;updateHintButton();toast("Video complete — one hint earned.")}else toast("Sponsored video complete.")}},1000);$("#adExit").onclick=()=>{clearInterval(state.adTimer);state.adTimer=null;$("#adFrame").src="about:blank";$("#rewardAd").classList.remove("open");toast(rewardHint?"Closed early — no hint earned. Rewatch to unlock it.":"Advertisement closed.")};$("#adCta").onclick=()=>window.open(SPONSOR_URL,"_blank","noopener")}
document.addEventListener("DOMContentLoaded",()=>{renderStats();buildCurrent();setTimeout(()=>{const registered=localStorage.getItem("gwg_account_created")==="1";if(registered){$("#welcomeName").textContent=localStorage.getItem("gwg_name")||"Player";openModal("#welcomeBackModal")}else openModal("#accountModal")},350);setInterval(()=>{state.seconds++;$("#timer").textContent=formatTime(state.seconds)},1000)});
$$(".navbtn[data-game]").forEach(b=>b.onclick=()=>switchGame(b.dataset.game));$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");$("#profileBtn").onclick=()=>openModal("#accountModal");$("#hintBtn").onclick=hint;$("#checkBtn").onclick=checkAnswers;$("#newBtn").onclick=()=>{state.puzzle=(state.puzzle+1)%100;buildCurrent();toast("A new puzzle is ready.")};$("#difficulty").onchange=e=>{state.difficulty=e.target.value;buildCurrent()};$$("[data-close]").forEach(b=>b.onclick=closeModals);$$(".modal-backdrop").forEach(m=>m.onclick=e=>{if(e.target===m&&m.id!=="accountModal")m.classList.remove("open")});
$$(".tab").forEach(t=>t.onclick=()=>{$$(".tab").forEach(x=>x.classList.toggle("active",x===t));$("#joinForm").hidden=t.dataset.auth!=="join";$("#loginForm").hidden=t.dataset.auth!=="login"});$("#accountModal").addEventListener("pointerdown",enterFullScreen,{capture:true});
function suggestUsername(){const f=$("#first").value.trim().replace(/\W/g,""),l=$("#last").value.trim().replace(/\W/g,"");if(f||l)$("#username").value=(f+l+(dayNumber%100)).toLowerCase()}$("#first").addEventListener("input",suggestUsername);$("#last").addEventListener("input",suggestUsername);$$("[data-password]").forEach(b=>b.onclick=()=>{const i=$("#"+b.dataset.password);i.type=i.type==="password"?"text":"password";b.textContent=i.type==="password"?"Show":"Hide"});
$("#profileBtn").onclick=()=>{if(localStorage.getItem("gwg_account_created")==="1")openModal("#welcomeBackModal");else openModal("#accountModal")};
$("#welcomeBackModal").addEventListener("pointerdown",enterFullScreen,{capture:true});
$("#welcomePlay").onclick=$("#welcomeClose").onclick=()=>{$("#welcomeBackModal").classList.remove("open");enterFullScreen()};
$("#rewardAd").addEventListener("click",e=>{if(e.target===$("#rewardAd")){e.stopImmediatePropagation();$("#adExit").click()}},{capture:true});
$("#joinForm").addEventListener("submit",()=>localStorage.setItem("gwg_account_created","1"));
$("#loginForm").addEventListener("submit",()=>localStorage.setItem("gwg_account_created","1"));
$("#joinForm").onsubmit=e=>{e.preventDefault();const name=$("#username").value.trim();localStorage.setItem("gwg_name",name);$("#profileBtn").textContent=name;closeModals();enterFullScreen();toast("Welcome, "+name+"! Your puzzle is ready.")};$("#loginForm").onsubmit=e=>{e.preventDefault();const name=$("#loginUser").value.trim().split("@")[0];localStorage.setItem("gwg_name",name);$("#profileBtn").textContent=name;closeModals();enterFullScreen();toast("Welcome back, "+name+"!")};$("#skipBtn").onclick=()=>{closeModals();enterFullScreen();toast("Playing as a guest. Progress stays on this device.")};$("#continueBtn").onclick=()=>{$("#winModal").classList.remove("open");state.puzzle=(state.puzzle+1)%100;buildCurrent()};
const savedName=localStorage.getItem("gwg_name");if(savedName)$("#profileBtn").textContent=savedName;
$("#howBtn").onclick=()=>showInfo("How to Play","<p>Choose a game, select Easy, Medium, or Hard, and use Hint whenever you need help. Correct crossword words turn green automatically. Word Search and Memory Match check progress as you play. Use Check Answers for Crossword or Sudoku.</p>");$("#helpBtn").onclick=$("#howBtn").onclick;
$("#statsBtn").onclick=()=>{const s=state.stats;showInfo("Your Statistics","<p><b>"+s.completed+"</b> puzzles completed</p><p><b>"+s.totalScore.toLocaleString()+"</b> total points · Best score: <b>"+s.best.toLocaleString()+"</b></p><p>Current streak: <b>"+s.streak+" days</b></p><p>These statistics are stored only in this browser until Supabase is connected.</p>")};
$("#settingsBtn").onclick=()=>showInfo("Settings","<p><button class='action' onclick=\"document.documentElement.style.fontSize=document.documentElement.style.fontSize==='21px'?'18px':'21px'\">Toggle larger text</button></p><p><button class='action' onclick=\"document.body.style.filter=document.body.style.filter?'':'contrast(1.18)'\">Toggle extra contrast</button></p>");
$("#aboutBtn").onclick=()=>showInfo("About & Policies","<p>Golden Word Games provides recreational puzzles and is not medical advice. We use clear advertising labels and do not disguise ads as game controls.</p><p><b>Privacy:</b> This preview does not transmit account details. Passwords and phone numbers are never saved locally. Secure account storage, consent records, deletion controls, and a complete privacy policy must be configured with Supabase before public account collection.</p><p><b>Advertising:</b> Rewarded ads are optional, clearly labeled, and grant a hint only after completion. Future ads must follow the sponsor network's policies and provide required consent choices.</p>");$$(".ad").forEach(ad=>ad.onclick=()=>startRewardAd(false));
if(document.modelContext?.registerTool)document.modelContext.registerTool({name:"start_game",title:"Start a game",description:"Open a puzzle game.",inputSchema:{type:"object",properties:{game:{type:"string",enum:["crossword","wordsearch","sudoku","memory"]}},required:["game"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({game})=>{switchGame(game);return{opened:game,difficulty:state.difficulty,puzzle:state.puzzle+1}}}).catch?.(()=>{});
