const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const SUPABASE_URL="https://psmkyenatcpfcsohilkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_gBCXwgZHPtE7SjkhVyrMuA_ujsfp7QC";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const SITE_URL="https://goldenwordgames.netlify.app",browserSessionId=crypto.randomUUID(),visitStartedAt=Date.now();
let currentUser=null,currentGameSessionId=null,lastActiveAt=Date.now(),activeSeconds=0;
let playerToken=localStorage.getItem("gwg_player_token")||"";
const PROFILE_AVATARS=["🐶","🐱","🦊","🐻","🐼","🐨","🦁","🐯","🐮","🐷","🐸","🐵","🦉","🐧","🐦","🐰","🦋","🐢","🐬","🦜"];
const COUNTRIES="Afghanistan|Albania|Algeria|Andorra|Angola|Antigua and Barbuda|Argentina|Armenia|Australia|Austria|Azerbaijan|Bahamas|Bahrain|Bangladesh|Barbados|Belarus|Belgium|Belize|Benin|Bhutan|Bolivia|Bosnia and Herzegovina|Botswana|Brazil|Brunei|Bulgaria|Burkina Faso|Burundi|Cabo Verde|Cambodia|Cameroon|Canada|Central African Republic|Chad|Chile|China|Colombia|Comoros|Congo|Costa Rica|Croatia|Cuba|Cyprus|Czechia|Democratic Republic of the Congo|Denmark|Djibouti|Dominica|Dominican Republic|Ecuador|Egypt|El Salvador|Equatorial Guinea|Eritrea|Estonia|Eswatini|Ethiopia|Fiji|Finland|France|Gabon|Gambia|Georgia|Germany|Ghana|Greece|Grenada|Guatemala|Guinea|Guinea-Bissau|Guyana|Haiti|Honduras|Hungary|Iceland|India|Indonesia|Iran|Iraq|Ireland|Israel|Italy|Ivory Coast|Jamaica|Japan|Jordan|Kazakhstan|Kenya|Kiribati|Kuwait|Kyrgyzstan|Laos|Latvia|Lebanon|Lesotho|Liberia|Libya|Liechtenstein|Lithuania|Luxembourg|Madagascar|Malawi|Malaysia|Maldives|Mali|Malta|Marshall Islands|Mauritania|Mauritius|Mexico|Micronesia|Moldova|Monaco|Mongolia|Montenegro|Morocco|Mozambique|Myanmar|Namibia|Nauru|Nepal|Netherlands|New Zealand|Nicaragua|Niger|Nigeria|North Korea|North Macedonia|Norway|Oman|Pakistan|Palau|Palestine|Panama|Papua New Guinea|Paraguay|Peru|Philippines|Poland|Portugal|Qatar|Romania|Russia|Rwanda|Saint Kitts and Nevis|Saint Lucia|Saint Vincent and the Grenadines|Samoa|San Marino|Sao Tome and Principe|Saudi Arabia|Senegal|Serbia|Seychelles|Sierra Leone|Singapore|Slovakia|Slovenia|Solomon Islands|Somalia|South Africa|South Korea|South Sudan|Spain|Sri Lanka|Sudan|Suriname|Sweden|Switzerland|Syria|Taiwan|Tajikistan|Tanzania|Thailand|Timor-Leste|Togo|Tonga|Trinidad and Tobago|Tunisia|Turkey|Turkmenistan|Tuvalu|Uganda|Ukraine|United Arab Emirates|United Kingdom|United States|Uruguay|Uzbekistan|Vanuatu|Vatican City|Venezuela|Vietnam|Yemen|Zambia|Zimbabwe".split("|");
const US_STATES="Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|District of Columbia|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming".split("|");
let selectedProfileAvatar="🐶";
const dayNumber=Math.floor(Date.now()/86400000), saved=JSON.parse(localStorage.getItem("gwg_stats")||"{}");
const state={game:"crossword",difficulty:"easy",seconds:0,puzzle:dayNumber%100,moves:0,pairs:0,pairGoal:8,firstCard:null,lock:false,crossWords:[],wordTargets:[],hints:0,hintsUsed:0,bonusHints:0,adTimer:null,stats:{completed:saved.completed||0,best:saved.best||0,totalScore:saved.totalScore||0,streak:saved.streak||0,lastDay:saved.lastDay||0}};
const adConfig=window.GOLDEN_AD_CONFIG||{}, AD_PAGE_URL=adConfig.adPageUrl||"https://example.com/", SPONSOR_URL=adConfig.sponsorWebsiteUrl||AD_PAGE_URL, AD_DURATION=Math.max(5,Number(adConfig.durationSeconds)||30), AD_CTA_AFTER=Math.max(0,Number(adConfig.ctaAppearsAfterSeconds)||10);
const toast=msg=>{const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)};
const openModal=id=>$(id).classList.add("open"), closeModals=()=>$$(".modal-backdrop").forEach(m=>m.classList.remove("open"));
function enterFullScreen(){const el=document.documentElement;if(!document.fullscreenElement&&el.requestFullscreen)el.requestFullscreen().catch(()=>toast("Your browser did not allow full screen."))}
function fillCountries(select){select.innerHTML=["United States",...COUNTRIES.filter(x=>x!=="United States")].map(country=>"<option value='"+country+"'>"+country+"</option>").join("")}
function syncStateSelect(countrySelect,stateSelect,savedState=""){const isUS=countrySelect.value==="United States";stateSelect.disabled=!isUS;stateSelect.required=false;stateSelect.innerHTML=isUS?"<option value=''>Select state</option>"+US_STATES.map(state=>"<option>"+state+"</option>").join(""):"<option value=''>Not applicable</option>";if(isUS&&savedState)stateSelect.value=savedState}
function setupLocationFields(){[["#country","#state"],["#profileCountry","#profileState"]].forEach(([countryId,stateId])=>{const country=$(countryId),state=$(stateId);fillCountries(country);country.value="United States";syncStateSelect(country,state);country.onchange=()=>syncStateSelect(country,state)})}
function seeded(seed){return()=>{seed=Math.imul(seed^seed>>>15,1|seed);seed^=seed+Math.imul(seed^seed>>>7,61|seed);return((seed^seed>>>14)>>>0)/4294967296}}
const shuffle=(a,r=Math.random)=>a.map(v=>[r(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]), levelCount={easy:5,medium:7,hard:9};
const wordBanks={
easy:[["APPLE","A crisp fruit"],["TRAIN","Railway traveler"],["HOUSE","A place to live"],["WATER","Drink from a glass"],["MUSIC","Pleasant sound"],["BEACH","Sandy shore"],["CHAIR","A seat"],["SMILE","Happy expression"],["CLOCK","It tells time"],["RIVER","Flowing water"],["BREAD","Bakery staple"],["LIGHT","Opposite of dark"],["GARDEN","Place for flowers"],["FAMILY","Parents and children"],["ROAD","Route for cars"]],
medium:[["LIBERTY","Freedom"],["JOURNEY","A long trip"],["HARVEST","Gathering crops"],["THEATER","Place for a stage show"],["MOUNTAIN","Very high land"],["HISTORY","Study of the past"],["BASEBALL","American pastime"],["BALLOON","Inflated party decoration"],["COUNTRY","A nation"],["AIRPORT","Place to catch a flight"],["MORNING","Start of the day"],["LIBRARY","Home of many books"],["PICNIC","Outdoor meal"],["HIGHWAY","Major road"],["WEATHER","Outdoor conditions"]],
hard:[["BLUEPRINT","Detailed building plan"],["DISCOVERY","Finding something new"],["LANDSCAPE","Visible features of land"],["KNOWLEDGE","Facts and understanding"],["CELEBRATE","Mark a happy occasion"],["ADVENTURE","An exciting experience"],["COMMUNITY","People living together"],["TRADITION","Custom passed through generations"],["WILDERNESS","Uncultivated natural region"],["PRESIDENT","Head of the US executive branch"],["TELESCOPE","Instrument for distant objects"],["MASTERPIECE","Outstanding creative work"],["NAVIGATION","Finding a route"],["MEMORABLE","Worth remembering"],["GENERATION","People born in a similar period"]]};
function placeCrossword(entries){const size=15,board=Array.from({length:size},()=>Array(size).fill("")),placed=[],first=entries[0],sx=Math.floor((size-first[0].length)/2),sy=7;first[0].split("").forEach((c,i)=>board[sy][sx+i]=c);placed.push({word:first[0],clue:first[1],x:sx,y:sy,dir:"across"});
for(const [word,clue] of entries.slice(1)){let done=false;for(let pi=0;pi<placed.length&&!done;pi++){const p=placed[pi];for(let a=0;a<word.length&&!done;a++)for(let b=0;b<p.word.length&&!done;b++)if(word[a]===p.word[b]){const dir=p.dir==="across"?"down":"across",x=p.x+(p.dir==="across"?b:0)-(dir==="across"?a:0),y=p.y+(p.dir==="down"?b:0)-(dir==="down"?a:0);if(x<0||y<0||(dir==="across"&&x+word.length>size)||(dir==="down"&&y+word.length>size))continue;let ok=true;for(let k=0;k<word.length;k++){const xx=x+(dir==="across"?k:0),yy=y+(dir==="down"?k:0),v=board[yy][xx];if(v&&v!==word[k])ok=false}if(ok){word.split("").forEach((c,k)=>board[y+(dir==="down"?k:0)][x+(dir==="across"?k:0)]=c);placed.push({word,clue,x,y,dir});done=true}}}}return{board,placed}}
function makeCrossword(){const r=seeded(state.puzzle*97+dayNumber+({easy:1,medium:2,hard:3}[state.difficulty])*1009),selected=shuffle(wordBanks[state.difficulty],r).slice(0,levelCount[state.difficulty]),built=placeCrossword(selected),board=built.board,placed=built.placed;state.crossWords=placed;const used=[];board.forEach((row,y)=>row.forEach((v,x)=>{if(v)used.push([x,y])}));const minX=Math.min(...used.map(v=>v[0])),maxX=Math.max(...used.map(v=>v[0])),minY=Math.min(...used.map(v=>v[1])),maxY=Math.max(...used.map(v=>v[1])),nums=new Map();placed.forEach((p,i)=>nums.set(p.x+","+p.y,i+1));const g=$("#crossGrid");g.innerHTML="";g.style.gridTemplateColumns="repeat("+(maxX-minX+1)+",1fr)";
for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const v=board[y][x],c=document.createElement("div");c.className=v?"cell":"cell block";c.dataset.xy=x+","+y;if(v){if(nums.has(c.dataset.xy))c.innerHTML="<span class='num'>"+nums.get(c.dataset.xy)+"</span>";const input=document.createElement("input");input.maxLength=1;input.dataset.answer=v;input.setAttribute("aria-label","Crossword square");input.oninput=()=>{input.value=input.value.replace(/[^a-z]/i,"").toUpperCase();markCrossWords()};c.appendChild(input)}g.appendChild(c)}
const fill=(id,dir)=>{$(id).innerHTML=placed.map((p,i)=>p.dir===dir?"<button class='clue'><b>"+(i+1)+".</b>"+p.clue+"</button>":"").join("")};fill("#acrossClues","across");fill("#downClues","down")}
function markCrossWords(){let solved=0;state.crossWords.forEach(p=>{let ok=true;for(let k=0;k<p.word.length;k++){const key=(p.x+(p.dir==="across"?k:0))+","+(p.y+(p.dir==="down"?k:0)),inp=$(".cell[data-xy='"+key+"'] input");if(!inp||inp.value!==p.word[k])ok=false}if(ok){solved++;for(let k=0;k<p.word.length;k++){const key=(p.x+(p.dir==="across"?k:0))+","+(p.y+(p.dir==="down"?k:0)),cell=$(".cell[data-xy='"+key+"']");if(cell)cell.classList.add("correct")}}});if(solved===state.crossWords.length&&solved)completeGame()}
const themes=[["American Road Trip",["HIGHWAY","MOTEL","TEXAS","BEACH","CANYON","TRAVEL","ROUTE","MAP"]],["At the Garden",["FLOWER","ROSE","SOIL","SEED","WATER","GREEN","BLOOM","SUN"]],["Classic Movies",["SCREEN","ACTOR","SCENE","TICKET","DRAMA","COMEDY","FILM","STAR"]],["Sunday Kitchen",["COFFEE","BREAD","PLATE","SPOON","APPLE","DINNER","RECIPE","OVEN"]],["Great Outdoors",["TRAIL","RIVER","CABIN","EAGLE","FOREST","LAKE","CAMP","HIKING"]]];
function makeWords(){const r=seeded(state.puzzle*181+dayNumber),themeData=themes[state.puzzle%themes.length],theme=themeData[0],bank=themeData[1],count=levelCount[state.difficulty];state.wordTargets=shuffle(bank,r).slice(0,Math.min(count,bank.length));$("#wordsearch .game-meta").innerHTML="<span>Find: <b>"+state.wordTargets.length+" words</b></span><span>Theme: <b>"+theme+"</b></span>";const size=10,rows=Array.from({length:size},()=>Array.from({length:size},()=>String.fromCharCode(65+Math.floor(r()*26)))),positions={};state.wordTargets.forEach((w,i)=>{const row=(i*2+Math.floor(r()*2))%size,start=Math.floor(r()*(size-w.length+1));positions[w]=[];w.split("").forEach((c,j)=>{rows[row][start+j]=c;positions[w].push(row*size+start+j)})});state.wordPositions=positions;const g=$("#wordGrid");g.innerHTML="";rows.flat().forEach((l,i)=>{const b=document.createElement("button");b.className="letter";b.textContent=l;b.dataset.index=i;b.onclick=()=>{b.classList.toggle("marked");checkFoundWords()};g.appendChild(b)});$("#wordBank").innerHTML=state.wordTargets.map(w=>"<span class='word-chip' data-word='"+w+"'>"+w+"</span>").join("")}
function checkFoundWords(){let found=0;state.wordTargets.forEach(w=>{const ok=state.wordPositions[w].every(i=>$$(".letter")[i].classList.contains("marked"));$("[data-word='"+w+"']").classList.toggle("found",ok);if(ok)found++});if(found===state.wordTargets.length)completeGame()}
function makeSudoku(){const base="123456789456789123789123456234567891567891234891234567345678912678912345912345678",shift=(state.puzzle+({easy:1,medium:3,hard:5}[state.difficulty]))%9;state.sudokuSolution=[...base].map(n=>((+n+shift-1)%9)+1).join("");const removals={easy:36,medium:48,hard:56}[state.difficulty],r=seeded(state.puzzle*313+dayNumber),holes=new Set(shuffle([...Array(81).keys()],r).slice(0,removals)),g=$("#sudokuGrid");g.innerHTML="";[...state.sudokuSolution].forEach((v,i)=>{const input=document.createElement("input");input.className="sudoku-cell"+(!holes.has(i)?" given":"");input.value=holes.has(i)?"":v;input.maxLength=1;input.inputMode="numeric";input.readOnly=!holes.has(i);input.dataset.answer=v;input.oninput=()=>{input.value=input.value.replace(/[^1-9]/g,"");$("#remaining").textContent=$$(".sudoku-cell").filter(x=>!x.value).length;if($$(".sudoku-cell").every(x=>x.value===x.dataset.answer))completeGame()};g.appendChild(input)});$("#remaining").textContent=removals}
const symbols=["♣","★","♪","☀","◆","♥","⚓","☕","♠","●"];
function makeMemory(){state.moves=0;state.pairs=0;state.firstCard=null;state.pairGoal={easy:6,medium:8,hard:10}[state.difficulty];$("#moves").textContent="0";$("#pairs").textContent="0 / "+state.pairGoal;const r=seeded(state.puzzle*421+dayNumber),deck=shuffle([...symbols.slice(0,state.pairGoal),...symbols.slice(0,state.pairGoal)],r),g=$("#memoryGrid");g.style.gridTemplateColumns="repeat("+(state.pairGoal===10?5:4)+",1fr)";g.innerHTML="";deck.forEach(v=>{const b=document.createElement("button");b.className="memory-card";b.dataset.symbol=v;b.textContent="?";b.onclick=()=>flipCard(b);g.appendChild(b)})}
function flipCard(b){if(state.lock||b.classList.contains("matched")||b===state.firstCard)return;b.textContent=b.dataset.symbol;b.classList.add("revealed");if(!state.firstCard){state.firstCard=b;return}state.moves++;$("#moves").textContent=state.moves;if(state.firstCard.dataset.symbol===b.dataset.symbol){b.classList.add("matched");state.firstCard.classList.add("matched");state.firstCard=null;state.pairs++;$("#pairs").textContent=state.pairs+" / "+state.pairGoal;if(state.pairs===state.pairGoal)completeGame()}else{state.lock=true;const a=state.firstCard;setTimeout(()=>{a.textContent=b.textContent="?";a.classList.remove("revealed");b.classList.remove("revealed");state.firstCard=null;state.lock=false},650)}}
const meta={crossword:["Daily Puzzle #","Crossword","Fill the crossing words using the Across and Down clues."],wordsearch:["Daily Puzzle #","Word Search","Tap every letter in each hidden word."],sudoku:["Daily Puzzle #","Sudoku","Fill every row, column, and box with the numbers 1 through 9."],memory:["Brain Boost #","Memory Match","Turn over two cards at a time and find every matching pair."]};
function resetTimer(){state.seconds=0;state.hintsUsed=0;state.bonusHints=0;updateHintButton()} function buildCurrent(){resetTimer();if(state.game==="crossword")makeCrossword();if(state.game==="wordsearch")makeWords();if(state.game==="sudoku")makeSudoku();if(state.game==="memory")makeMemory();$("#eyebrow").textContent=meta[state.game][0]+(state.puzzle+1)+" · refreshes daily"}
function switchGame(game){state.game=game;$$(".navbtn[data-game]").forEach(b=>b.classList.toggle("active",b.dataset.game===game));$$(".game-view").forEach(v=>v.classList.toggle("active",v.id===game));$("#gameTitle").textContent=meta[game][1];$("#gameSub").textContent=meta[game][2];$("#sidebar").classList.remove("open");buildCurrent();startGameTracking()}
function checkAnswers(){let right=0,total=0;if(state.game==="crossword"){$$("#crossGrid input").forEach(i=>{total++;const c=i.parentElement;c.classList.remove("correct","wrong");if(i.value===i.dataset.answer){right++;c.classList.add("correct")}else if(i.value)c.classList.add("wrong")})}else if(state.game==="sudoku"){$$(".sudoku-cell").forEach(i=>{if(!i.readOnly){total++;i.style.background=i.value===i.dataset.answer?"#d8f2e3":i.value?"#ffd9d6":"white";if(i.value===i.dataset.answer)right++}})}else return toast("Words and pairs are checked automatically.");toast(right+" of "+total+" entries are correct.")}
function updateHintButton(){const free=Math.max(0,2-state.hintsUsed);$("#hintBtn").textContent=free?"Hint ("+free+" free)":state.bonusHints?"Use earned hint":"Watch ad for hint"}
function performHint(){state.hints++;if(state.game==="crossword"){const x=$$("#crossGrid input").find(i=>!i.value);if(x){x.value=x.dataset.answer;x.style.color="#e96f2d";markCrossWords()}}else if(state.game==="sudoku"){const x=$$(".sudoku-cell").find(i=>!i.value);if(x){x.value=x.dataset.answer;x.style.color="#e96f2d"}}else if(state.game==="wordsearch")toast("Look from left to right across each row.");else toast("Try remembering the position, not just the symbol.")}
function hint(){trackEvent("hint_requested",{free_hints_used:state.hintsUsed});if(state.hintsUsed<2){state.hintsUsed++;performHint();updateHintButton();return}if(state.bonusHints>0){state.bonusHints--;performHint();updateHintButton();return}startRewardAd(true)}
function winningSound(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.setValueAtTime(523,a.currentTime);o.frequency.setValueAtTime(659,a.currentTime+.12);o.frequency.setValueAtTime(784,a.currentTime+.24);g.gain.setValueAtTime(.08,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.55);o.start();o.stop(a.currentTime+.56)}catch(e){}}
const formatTime=s=>String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0");
function completeGame(){if($("#winModal").classList.contains("open"))return;const mult={easy:1,medium:1.4,hard:1.8}[state.difficulty],score=Math.max(100,Math.round((1400-state.seconds*3-state.hints*75)*mult));state.stats.completed++;state.stats.totalScore+=score;state.stats.best=Math.max(state.stats.best,score);if(state.stats.lastDay===dayNumber-1)state.stats.streak++;else if(state.stats.lastDay!==dayNumber)state.stats.streak=1;state.stats.lastDay=dayNumber;localStorage.setItem("gwg_stats",JSON.stringify(state.stats));$("#winScore").textContent=score.toLocaleString()+" points";$("#winMessage").textContent="Completed in "+formatTime(state.seconds)+" on "+state.difficulty+" difficulty.";$("#winModal").classList.add("open");$("#confetti").classList.add("show");winningSound();trackGameComplete(score);setTimeout(()=>$("#confetti").classList.remove("show"),2500);renderStats()}
function showInfo(title,html){$("#infoTitle").textContent=title;$("#infoBody").innerHTML=html;openModal("#infoModal")}
function renderStats(){const names=["MapleSue","RoadTripRay","BlueJay55","GardenGal","JazzFan","TexasTom","CarolP","PuzzlePat","SunnySam","OhioRose","LakeLou","BostonBill","NanaJo","CoachKen","DaisyM","SilverFox","JuneB","MaineMike","HappyHal","WordWiz"];$("#rankings").innerHTML=names.slice(0,5).map((n,i)=>"<div class='rank-row'><b>"+(i+1)+"</b><span class='avatar'>"+n[0]+"</span><span>"+n+"</span><span class='score'>"+(1620-i*47).toLocaleString()+"</span></div>").join("");$(".streak strong").textContent=state.stats.streak+"-day streak"}
function startRewardAd(rewardHint=false){if(state.adTimer)clearInterval(state.adTimer);let n=AD_DURATION;enterFullScreen();$("#adFrame").src=AD_PAGE_URL;$("#adCount").textContent=n;$("#adStatus").textContent=rewardHint?"Watch completely to earn a hint":"Sponsored game preview";$("#adCta").classList.remove("show");openModal("#rewardAd");state.adTimer=setInterval(()=>{n--;$("#adCount").textContent=n;if(AD_DURATION-n>=AD_CTA_AFTER)$("#adCta").classList.add("show");if(n<=0){clearInterval(state.adTimer);state.adTimer=null;$("#adFrame").src="about:blank";$("#rewardAd").classList.remove("open");if(rewardHint){state.bonusHints++;updateHintButton();toast("Video complete — one hint earned.")}else toast("Sponsored video complete.")}},1000);$("#adExit").onclick=()=>{clearInterval(state.adTimer);state.adTimer=null;$("#adFrame").src="about:blank";$("#rewardAd").classList.remove("open");toast(rewardHint?"Closed early — no hint earned. Rewatch to unlock it.":"Advertisement closed.")};$("#adCta").onclick=()=>window.open(SPONSOR_URL,"_blank","noopener")}
function accountName(user){return user?.user_metadata?.username||user?.user_metadata?.name||user?.user_metadata?.full_name||user?.email?.split("@")[0]||"Player"}
function accountAvatar(user){return PROFILE_AVATARS.includes(user?.user_metadata?.avatar)?user.user_metadata.avatar:"🐶"}
function playerAsUser(player){return player?{id:player.id,email:player.email||"",user_metadata:{...player,full_name:player.name}}:null}
function showSignedInUser(user){const name=accountName(user),avatar=accountAvatar(user);localStorage.setItem("gwg_name",name);localStorage.setItem("gwg_avatar",avatar);$("#profileName").textContent=name;$("#profileAvatar").textContent=avatar;$("#welcomeName").textContent=name}
function renderAvatarPicker(){const picker=$("#avatarPicker");picker.innerHTML="";PROFILE_AVATARS.forEach(avatar=>{const button=document.createElement("button");button.type="button";button.className="avatar-choice"+(avatar===selectedProfileAvatar?" selected":"");button.textContent=avatar;button.setAttribute("role","radio");button.setAttribute("aria-label","Choose "+avatar+" avatar");button.setAttribute("aria-checked",avatar===selectedProfileAvatar?"true":"false");button.onclick=()=>{selectedProfileAvatar=avatar;$("#profilePreview").textContent=avatar;renderAvatarPicker()};picker.appendChild(button)})}
function openProfile(){if(!currentUser)return openModal("#accountModal");const m=currentUser.user_metadata||{},country=m.country||"United States";selectedProfileAvatar=accountAvatar(currentUser);$("#profilePreview").textContent=selectedProfileAvatar;$("#profileFullName").value=m.name||m.full_name||[m.first_name,m.last_name].filter(Boolean).join(" ")||"";$("#profileUsername").value=accountName(currentUser);$("#profileAge").value=m.age||50;$("#profileEmail").value=currentUser.email||"";$("#profilePhone").value=(m.phone||"").replace(/^\+1/,"");$("#profileAddressLine1").value=m.address_line1||m.address||"";$("#profileCity").value=m.city||"";$("#profileCountry").value=country;syncStateSelect($("#profileCountry"),$("#profileState"),m.state||"");$("#profileZipCode").value=m.zip_code||"";renderAvatarPicker();closeModals();openModal("#profileModal")}
async function saveProfileRecord(user,profile){if(!user)return;const {error}=await supabaseClient.from("profiles").upsert({user_id:user.id,email:user.email,...profile,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(error)console.info("Profiles table is not ready yet.")}
async function safeInsert(table,row){if(!currentUser)return null;const {data,error}=await supabaseClient.from(table).insert(row).select().maybeSingle();if(error){console.info("Tracking table not ready:",table);return null}return data}
async function startVisitTracking(){if(!currentUser)return;await supabaseClient.from("user_sessions").upsert({id:browserSessionId,user_id:currentUser.id,started_at:new Date(visitStartedAt).toISOString(),last_active_at:new Date().toISOString(),active_seconds:activeSeconds,user_agent:navigator.userAgent},{onConflict:"id"});await trackEvent("website_opened");await startGameTracking()}
async function trackEvent(eventType,eventData={}){return safeInsert("game_events",{user_id:currentUser?.id,session_id:browserSessionId,game_session_id:currentGameSessionId,event_type:eventType,game_type:state.game,difficulty:state.difficulty,event_data:eventData})}
async function startGameTracking(){if(!currentUser)return;const row=await safeInsert("game_sessions",{user_id:currentUser.id,session_id:browserSessionId,game_type:state.game,puzzle_id:String(state.puzzle+1),difficulty:state.difficulty,started_at:new Date().toISOString()});currentGameSessionId=row?.id||null;await trackEvent("game_started")}
async function trackGameComplete(score){if(!currentUser)return;if(currentGameSessionId)await supabaseClient.from("game_sessions").update({completed:true,completed_at:new Date().toISOString(),duration_seconds:state.seconds,score,hints_used:state.hints}).eq("id",currentGameSessionId).eq("user_id",currentUser.id);await trackEvent("game_completed",{score,duration_seconds:state.seconds,hints_used:state.hints})}
async function restoreAccount(){currentUser=null;if(playerToken){const {data}=await supabaseClient.rpc("get_player_session",{p_token:playerToken});currentUser=playerAsUser(data)}if(currentUser){showSignedInUser(currentUser);startVisitTracking()}setTimeout(()=>{if(currentUser)openModal("#welcomeBackModal");else{localStorage.removeItem("gwg_name");localStorage.removeItem("gwg_avatar");localStorage.removeItem("gwg_player_token");playerToken="";$("#profileName").textContent="Guest";$("#profileAvatar").textContent="🐾";openModal("#accountModal")}},350)}
document.addEventListener("DOMContentLoaded",()=>{setupLocationFields();renderStats();buildCurrent();restoreAccount();setInterval(()=>{state.seconds++;$("#timer").textContent=formatTime(state.seconds)},1000)});
$$(".navbtn[data-game]").forEach(b=>b.onclick=()=>switchGame(b.dataset.game));$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");$("#profileBtn").onclick=()=>openModal("#accountModal");$("#hintBtn").onclick=hint;$("#checkBtn").onclick=()=>{trackEvent("answers_checked");checkAnswers()};$("#newBtn").onclick=()=>{trackEvent("game_abandoned",{elapsed_seconds:state.seconds});state.puzzle=(state.puzzle+1)%100;buildCurrent();startGameTracking();toast("A new puzzle is ready.")};$("#difficulty").onchange=e=>{trackEvent("difficulty_changed",{from:state.difficulty,to:e.target.value});state.difficulty=e.target.value;buildCurrent();startGameTracking()};$$("[data-close]").forEach(b=>b.onclick=closeModals);$$(".modal-backdrop").forEach(m=>m.onclick=e=>{if(e.target===m&&m.id!=="accountModal")m.classList.remove("open")});
$$(".tab").forEach(t=>t.onclick=()=>{$$(".tab").forEach(x=>x.classList.toggle("active",x===t));$("#joinForm").hidden=t.dataset.auth!=="join";$("#loginForm").hidden=t.dataset.auth!=="login"});$("#accountModal").addEventListener("pointerdown",enterFullScreen,{capture:true});
function suggestUsername(){const name=$("#name").value.trim().replace(/[^a-z0-9]/gi,"");if(name)$("#username").value=(name+(dayNumber%100)).toLowerCase()}$("#name").addEventListener("input",suggestUsername);$$("[data-password]").forEach(b=>b.onclick=()=>{const i=$("#"+b.dataset.password);i.type=i.type==="password"?"text":"password";b.textContent=i.type==="password"?"Show":"Hide"});
$("#profileBtn").onclick=()=>currentUser?openProfile():openModal("#accountModal");
$("#welcomeBackModal").addEventListener("pointerdown",enterFullScreen,{capture:true});
$("#welcomePlay").onclick=$("#welcomeClose").onclick=()=>{$("#welcomeBackModal").classList.remove("open");enterFullScreen()};
$("#editProfileBtn").onclick=openProfile;
$("#rewardAd").addEventListener("click",e=>{if(e.target===$("#rewardAd")){e.preventDefault();e.stopImmediatePropagation()}},{capture:true});
$("#joinForm").onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button[type=submit]"),name=$("#name").value.trim(),age=Number($("#age").value),username=$("#username").value.trim(),digits=$("#phone").value.replace(/\D/g,""),country=$("#country").value,stateValue=$("#state").value;if(digits.length!==10)return toast("Please enter a valid 10-digit US phone number.");if(!Number.isInteger(age)||age<18||age>120)return toast("Please enter an age from 18 to 120.");button.disabled=true;button.textContent="Creating ID…";const {data,error}=await supabaseClient.rpc("create_player_account",{p_username:username,p_password:$("#password").value,p_email:$("#joinEmail").value.trim(),p_name:name,p_phone:"+1"+digits,p_age:age,p_address_line1:$("#addressLine1").value.trim(),p_city:$("#city").value.trim(),p_state:stateValue,p_zip_code:$("#zipCode").value.trim(),p_country:country});button.disabled=false;button.textContent="Create My ID";if(error)return toast(error.message.includes("USERNAME_TAKEN")?"That username is already taken. Please choose another.":"Could not create your ID. Please try again.");playerToken=data.token;localStorage.setItem("gwg_player_token",playerToken);currentUser=playerAsUser(data.player);showSignedInUser(currentUser);closeModals();enterFullScreen();toast("Welcome, "+username+"! Your ID is ready.")};
$("#loginForm").onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button[type=submit]");button.disabled=true;button.textContent="Signing In…";const {data,error}=await supabaseClient.rpc("login_player",{p_username:$("#loginUser").value.trim(),p_password:$("#loginPass").value});button.disabled=false;button.textContent="Sign In";if(error)return toast("Incorrect username or password.");playerToken=data.token;localStorage.setItem("gwg_player_token",playerToken);currentUser=playerAsUser(data.player);showSignedInUser(currentUser);closeModals();enterFullScreen();toast("Welcome back, "+accountName(currentUser)+"!")};$("#skipBtn").onclick=()=>{closeModals();enterFullScreen();toast("Playing as a guest. Progress stays on this device.")};$("#signOutBtn").onclick=async()=>{if(playerToken)await supabaseClient.rpc("logout_player",{p_token:playerToken});playerToken="";currentUser=null;localStorage.removeItem("gwg_player_token");localStorage.removeItem("gwg_name");localStorage.removeItem("gwg_avatar");$("#profileName").textContent="Guest";$("#profileAvatar").textContent="🐾";closeModals();openModal("#accountModal");toast("You have been signed out.")};$("#continueBtn").onclick=()=>{$("#winModal").classList.remove("open");state.puzzle=(state.puzzle+1)%100;buildCurrent()};
const savedName=localStorage.getItem("gwg_name"),savedAvatar=localStorage.getItem("gwg_avatar");if(savedName)$("#profileName").textContent=savedName;if(savedAvatar)$("#profileAvatar").textContent=savedAvatar;
$$("[data-provider]").forEach(button=>button.onclick=async()=>{const provider=button.dataset.provider;button.disabled=true;const {error}=await supabaseClient.auth.signInWithOAuth({provider,options:{redirectTo:SITE_URL}});if(error){button.disabled=false;toast(provider.charAt(0).toUpperCase()+provider.slice(1)+" login is not configured yet.")}});
$("#profileForm").onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button[type=submit]"),digits=$("#profilePhone").value.replace(/\D/g,""),age=Number($("#profileAge").value),country=$("#profileCountry").value,stateValue=$("#profileState").value;if(digits.length!==10)return toast("Please enter a valid 10-digit US phone number.");button.disabled=true;button.textContent="Saving…";const {data,error}=await supabaseClient.rpc("update_player_profile",{p_token:playerToken,p_username:$("#profileUsername").value.trim(),p_name:$("#profileFullName").value.trim(),p_phone:"+1"+digits,p_age:age,p_avatar:selectedProfileAvatar,p_address_line1:$("#profileAddressLine1").value.trim(),p_city:$("#profileCity").value.trim(),p_state:stateValue,p_zip_code:$("#profileZipCode").value.trim(),p_country:country});button.disabled=false;button.textContent="Save Profile";if(error)return toast(error.message.includes("USERNAME_TAKEN")?"That username is already taken.":"Could not save your profile.");currentUser=playerAsUser(data);showSignedInUser(currentUser);closeModals();enterFullScreen();toast("Profile updated.")};
setInterval(async()=>{if(!currentUser||document.visibilityState!=="visible")return;const now=Date.now(),increment=Math.min(30,Math.round((now-lastActiveAt)/1000));activeSeconds+=Math.max(0,increment);lastActiveAt=now;await supabaseClient.from("user_sessions").update({last_active_at:new Date().toISOString(),active_seconds:activeSeconds}).eq("id",browserSessionId).eq("user_id",currentUser.id)},30000);
document.addEventListener("visibilitychange",()=>{lastActiveAt=Date.now()});
$("#howBtn").onclick=()=>showInfo("How to Play","<p>Choose a game, select Easy, Medium, or Hard, and use Hint whenever you need help. Correct crossword words turn green automatically. Word Search and Memory Match check progress as you play. Use Check Answers for Crossword or Sudoku.</p>");$("#helpBtn").onclick=$("#howBtn").onclick;
$("#statsBtn").onclick=()=>{const s=state.stats;showInfo("Your Statistics","<p><b>"+s.completed+"</b> puzzles completed</p><p><b>"+s.totalScore.toLocaleString()+"</b> total points · Best score: <b>"+s.best.toLocaleString()+"</b></p><p>Current streak: <b>"+s.streak+" days</b></p><p>These statistics are stored only in this browser until Supabase is connected.</p>")};
$("#settingsBtn").onclick=()=>showInfo("Settings","<p><button class='action' onclick=\"document.documentElement.style.fontSize=document.documentElement.style.fontSize==='21px'?'18px':'21px'\">Toggle larger text</button></p><p><button class='action' onclick=\"document.body.style.filter=document.body.style.filter?'':'contrast(1.18)'\">Toggle extra contrast</button></p>");
$("#aboutBtn").onclick=()=>showInfo("About & Policies","<p>Golden Word Games provides recreational puzzles and is not medical advice. We use clear advertising labels and do not disguise ads as game controls.</p><p><b>Privacy:</b> Account authentication is securely handled by Supabase. Passwords are never stored in this browser or in our profile tables. Name, email, username, and phone details are used to provide the account service.</p><p><b>Advertising:</b> Rewarded ads are optional, clearly labeled, and grant a hint only after completion. Future ads must follow the sponsor network's policies and provide required consent choices.</p>");$$(".ad").forEach(ad=>ad.onclick=()=>startRewardAd(false));
if(document.modelContext?.registerTool)document.modelContext.registerTool({name:"start_game",title:"Start a game",description:"Open a puzzle game.",inputSchema:{type:"object",properties:{game:{type:"string",enum:["crossword","wordsearch","sudoku","memory"]}},required:["game"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({game})=>{switchGame(game);return{opened:game,difficulty:state.difficulty,puzzle:state.puzzle+1}}}).catch?.(()=>{});
